version: "3"
services:
  tests:
    build:
      context: .
    volumes:
      - ".:/plugin"
  lint:
    image: "buildkite/plugin-linter"
    command: ["--id", "twonds/github-repository-dispatch"]
    volumes:
      - ".:/plugin:ro"
